# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true


markdown: rdiscount
highlighter: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]



# Setup
title:               Aakarsh Nair
tagline:             ''
description:         'A collection of notes and ramblings collected from a random walk through readings of various sorts.  Made by <a href="https://twitter.com/aakarsh" target="_blank">@aakarsh</a>.'
url:                 'http://www.aakarshn.com'
baseurl:             ''
paginate:            5
gravatar_url:        'http://www.gravatar.com/avatar/651ea8be2ad101903021054626f0e1aa.png'
# About/contact
author:
  name:              Aakarsh Nair
  url:               https://twitter.com/aakarsh
  email:             aakarsh.nair@gmail.com
  twitter:           aakarsh
  resume:            res.pdf
github:
  repo:              'http://github.com/aakarsh'

# Custom vars
version:             1.0.0
